### ISSUE TITLE
Crashing when viewing inside Catalogue mod list

### ISSUE THREAD

**Issue by WarmIceCream** [Affehund/VoidTotem#14]
Seems to cause crashing when I scroll down to it in my mods list - potentially some clashing with [XP Tome](https://www.curseforge.com/minecraft/mc-mods/xp-tome), as removing this mod or Void Totem stopped the crashing 

mc 1.18.1, forge 39.1.2 (v1.2.0 of VoidTotem)
[Crash log](https://drive.google.com/file/d/1ZECNS7WDJq6L1UF6nUSSlKEdoOHp4-k_/view?usp=sharing)

**Comment by Affehund** [comment]
I can't reproduce this issue on the newest forge version with Void Totem and XP Tome installed. Did you try to delete the old void totem config? And could you maybe make a short video so I can see what exactly happens to reproduce the crash?

**Comment by WarmIceCream** [comment]
Here's a video of what happens, as soon as the mod comes into view on the list it crashes.
https://user-images.githubusercontent.com/63678263/166065912-03e3659a-50b3-44c9-a6bc-9d107ded8ca3.mp4

Also looks like Not Enough Crashes seems to think that Catalogue and Quark have something to do with the issue too (and after testing, it seems removing any one of the 4 mods stops the crashing)

**Comment by Affehund** [comment]
Ok, that's a very strange issue. I still can't reproduce it. 
I assume it doesnt't crash when not using Catalogue. Can you try this? 
Maybe MrCrayfish/Catalogue#29 has to do with it?

**Comment by WarmIceCream** [comment]
I have tried omitting Catalogue, Quark, Void Totem and XP Tome each individually, and the crash doesn't happen when any one of them isn't there

**Comment by Affehund** [comment]
Ok, I will have a look what I can do. Can you maybe send me your full modlist or something like this, so that I can maybe reproduce the crash.

**Comment by WarmIceCream** [comment]
The mod list is at the bottom of the crash log via the link in the original post, but I've also put all the mods into a zip file https://drive.google.com/file/d/1qOTkGSoaMLzZdQWTLDYyxgS8urZhWPqB/view?usp=sharing

**Comment by Affehund** [comment]
Ok, so I could finally reproduce the crash. It obviously is an issue with Catalogue mod. And I probably won't be able to fix it on my side. Maybe you can open an issue on their github? 
The weird thing about is that it happens so rarely. Only when some specific mods are installed. 

For the next time can you please provide a link to an exported curseforge profile, as it's not safe to download like 200 mods from a link. Then I can just import it into curseforge.

**Comment by WarmIceCream** [comment]
Apologies about that, not too familiar with the curseforge desktop, so I don't have a profile made for my modpack - though that would probably make things a lot easier

**Comment by Affehund** [comment]
I recommend you do either use the 1.18.1-1.1.2 version or to upgrade to the 1.18.2 version as this error only occurs in this specific version of the mod.
