### ISSUE TITLE
Hard Crash: "voidtotem:additional_totems used before it was bound" on voidtotem-forge-1.18.1-1.2.0

### ISSUE THREAD

**Issue by endarz** [Affehund/VoidTotem#15]
Subject says it all. Game hard crashes when trying to access shaders (through Optifine).

At the time I wrote the comment on the CurseForge page, I had not tested if it was just a problem with Optifine 1.18.1, so I'll test it and update this issue accordingly with more info. This is likely a problem stemming from Optifine, but I will verify.

Crash log:
[crash-2022-05-07_23.17.21-client.txt](https://github.com/Affehund/VoidTotem/files/8647363/crash-2022-05-07_23.17.21-client.txt)

**Comment by endarz** [comment]
This is not an Optifine issue; the issue occurs again as soon as one clicks on the Options button and goes into Video Settings.

**Comment by Affehund** [comment]
Thank you for submitting this issue. Which version of the mod are you using? And forge or fabric?

**Comment by Affehund** [comment]
Could be the same problem as with affehund/voidtotem#14, assuming you are using voidtotem-forge-1.18.1-1.2.0.

**Comment by endarz** [comment]
> Thank you for submitting this issue. Which version of the mod are you using? And forge or fabric?

Forge version.

> Could be the same problem as with #14, assuming you are using voidtotem-forge-1.18.1-1.2.0.

That's the correct version. I _did_ check the other issue, but I never opened the user's crash log to see that it was the same problem, so that's my bad. When I get time today, I will check to see what mod (or mods) are not playing nice with Void Totem.

I do not use Catalogue, but I am running XP Tome and Quark in addition to Void Totem, so there's that.

**Comment by Affehund** [comment]
Don't worry, it's probably a bigger issue in my code. Seems to be similiar to the other issue.

**Comment by Sshmoob** [comment]
I said this in the curseforge comments, but clicking other buttons crashes the game as well. Sometimes certain buttons do work and sometimes they crash. I have had it happen when I click the options button, resource pack button, changing resource packs, and the multiplayer button so far. To prevent this I have been using 1.1.2 instead.

**Comment by Affehund** [comment]
I have been testing around a lot the last few days and I also noticed it crashes with other buttons / actions, too. Thank you anyways for pointing this out. And yes I seems to happen in version 1.18.1-1.2.0. Older versions or the 1.18.2 version are not affected.

**Comment by Affehund** [comment]
I think the best thing would be to change to the 1.18.1-1.1.2 or to the 1.18.2 version as it only seems to occur in this specific version and I don't see why it should crash or why it should want to access the tag when changing resourcepacks / shaders.

**Comment by endarz** [comment]
Alright, I'll do that. Going to go ahead and close this issue out, too.
