### ISSUE TITLE
Void Totem does not work with McDoom

### ISSUE THREAD

**Issue by pokesmells** [Affehund/VoidTotem#20]
**Fabric Version:** 0.14.17 - fabric-api-0.76.0+1.19.2
**Minecraft Version:** 1.19.2
**Mod Version:** voidtotem-fabric-1.19.2-2.1.0
**OS:** Windows 11
**Launcher:** Curseforge

**Describe the bug:**
When I fall into the void with the totem in my offhand, the totem doesn't work whatsoever.
https://user-images.githubusercontent.com/33227568/226488654-2cb7338e-6bee-435c-b92f-32658aebf167.mp4

**Relevant Logs:**
https://mclo.gs/EZGqKHK

**Comment by Affehund** [comment]
As you also mentioned in the discord, it seems to be an issue with McDoom.

**Comment by Affehund** [comment]
I created an issue on their GitHub: AzureDoom/MCDoom/issues/91

**Comment by Affehund** [comment]
Should be fixed with https://github.com/AzureDoom/MCDoom/commit/c2bbf97abe7ee1e3297f1707fe11583e65ba9975
