### ISSUE TITLE
Using the totem of undying grants BOTH Postmortal advancements

### ISSUE THREAD

**Issue by Dejeh** [Affehund/VoidTotem#4]
Fabric v0.12.12
voidtotem-1.18.1-1.1.0

**Comment by Affehund** [comment]
It was actually intended that you also get the vanilla Postmortal advancement when falling into to void. But I can could change this should it be deemed necessary.

**Comment by Dejeh** [comment]
No, using the vanilla totem grants both advancements. My fault for the misleading title

Like if I fall from the ground and I just have the vanilla totem, it works but gives both Postmortal 1 & 2 despite me not falling into the void or having the void totem on me.

**Comment by Affehund** [comment]
Oh, that makes more sense. That’s actually something I have never thought of.
Should be fixable by the next weekend.
Anyways thank you for reporting this issue!

**Comment by Affehund** [comment]
should be fixed with v1.18.1-1.1.1
