### ISSUE TITLE
postmortal advancements

### ISSUE THREAD

**Issue by BrokenDawn627** [Affehund/VoidTotem#5]
No matter what I do, I will always get this advancement.
In my modpack Infinity https://www.curseforge.com/minecraft/modpacks/infinity-fabric/files

**Comment by Affehund** [comment]
I will have a deeper look at this issue tomorrow. Maybe you can give me some more information in the meanwhile.
I assume you are using fabric and the latest version of the void totem 1.18.1 (voidtotem-1.18.1-1.1.1)? 
Could be similar to issue #4.

**Comment by Affehund** [comment]
I couldn't reproduce this issue using the newest version of the void totem mod and also testing it with the latest release with the infinity mod pack. Maybe you are using an outdated version.

**Comment by BrokenDawn627** [comment]
the mod version is 1.1.1. when I right-click some item I will get this advancement , such as using a bow or combat wands.

**Comment by Affehund** [comment]
Seems to be an issue with the advancement itself. I will release a new version soon. 
Thank you very much for reporting this issue.
