### ISSUE TITLE
Hope to support durability totem in end goblin traders

### ISSUE THREAD

**Issue by Q2297045667** [Affehund/VoidTotem#8]
item ID:
endgoblintraders:durability_totem

MOD link:
https://www.curseforge.com/minecraft/mc-mods/end-goblin-traders-fabric

**Comment by Q2297045667** [comment]
https://github.com/LimeAppleBoat/EndGoblinTraders/blob/1.18/src/main/generated/resources/data/endgoblintraders/trades/end_goblin_trader/legendary.json
He uses the form of packets

**Comment by Affehund** [comment]
You mean like being able to use the durability totem from end goblin traders? 
Or adding a trade for the void totem for end goblin traders? What would you use in exchange for the trading?

**Comment by Jab125** [comment]
will be supported from End Goblin Traders in 1.4.3 so nothing is needed on your end.

**Comment by Jab125** [comment]
those commits are painful

**Comment by Affehund** [comment]
That’s great. Thank you very much!

**Comment by Q2297045667** [comment]
Thank
